requires 'Mojolicious';
requires 'Mojo::Feed';
requires 'Mojo::SQLite';
requires 'Mojo::WebService::Twitter', '1.001';
requires 'Encode';
requires 'Fcntl';
requires 'Getopt::Long';
requires 'Pod::Usage';
requires 'FindBin';
requires 'lib';
