#!/usr/bin/perl

use Mojo::Base -base;
use Mojo::Feed;
use Mojo::SQLite;

my $rss_url = 'https://taz.de/!p4608;rss/';

my $sql = Mojo::SQLite->new('sqlite:test.db');
$sql->migrations->from_string(<<EOF)->migrate;
  -- 1 up
	create table items (
		id integer primary key autoincrement,
		guid text unique,
		published integer default 0,
		title text not null,
		link text not null
	);
  -- 1 down
	drop table items;
EOF

my $feed = Mojo::Feed->new( url => $rss_url );

for my $item ( $feed->items->reverse->each ) {
    $sql->db->query(
        'insert or ignore into items (guid, title, link) values (?,?,?)',
        $item->id, $item->title, $item->link );
}

exit 0;
